# Generated by Django 5.2.3 on 2025-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=250)),
                ('videoSlug', models.SlugField(default='unknown', max_length=250)),
                ('video_url', models.URLField()),
                ('format', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('quality', models.CharField(default='high', max_length=10)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('viewport_size', models.CharField(blank=True, max_length=20, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=20, null=True)),
                ('download_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('session_duration', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=1)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_info', models.JSONField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('download_successful', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user_ip', 'date'], name='app_userdow_user_ip_b43a21_idx'), models.Index(fields=['format', 'date'], name='app_userdow_format_bd8f8c_idx'), models.Index(fields=['is_mobile', 'date'], name='app_userdow_is_mobi_d17cab_idx')],
            },
        ),
    ]
